//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace invoice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerproduct
    {
        public int idcustomerproduct { get; set; }
        public int customer { get; set; }
        public int product { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual customerproduct customerproduct1 { get; set; }
        public virtual customerproduct customerproduct2 { get; set; }
    }
}
