//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace invoice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproduct
    {
        public int idproduct { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public string srno { get; set; }
    }
}
